### ISSUE TITLE
Fails with `order` property

### ISSUE THREAD

**Issue by tobias-kuendig** [filipac/oc-idehelper-plugin#2]
Given this model:

```php

class Topic extends Model
{
    public $hasMany = [
        'questions' => [Question::class, 'order' => 'sort_order ASC']
    ];
}
```

The models command seems to fail:

```bash
$ php artisan ide-helper:models --nowrite --reset --no-interaction

Exception: Class 'sort_order' not found
Could not analyze class OFFLINE\FAQ\Models\Question.

Trace:
#0 /app/vendor/october/rain/src/Database/Concerns/HasRelationships.php(426): Illuminate\Database\Eloquent\Model->newRelatedInstance('sort_order')
#1 /app/vendor/october/rain/src/Database/Concerns/HasRelationships.php(289): October\Rain\Database\Model->belongsTo('sort_order', NULL, NULL, 'sort')
#2 [internal function]: October\Rain\Database\Model->handleRelation('sort')
#3 /app/plugins/filipac/idehelper/src/Console/Commands/ModelsCommand.php(363): ReflectionMethod->invoke(Object(OFFLINE\FAQ\Models\Question), 'sort')
#4 /app/plugins/filipac/idehelper/src/Console/Commands/ModelsCommand.php(138): Filipac\IdeHelper\Console\Commands\ModelsCommand->generateDocs(Array, Array)
#5 [internal function]: Filipac\IdeHelper\Console\Commands\ModelsCommand->handle()
#6 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#7 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#9 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))
#10 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)
#11 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#12 /app/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#13 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /app/vendor/symfony/console/Application.php(1005): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /app/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(Filipac\IdeHelper\Console\Commands\ModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}
```

**Comment by filipac** [comment]
@tobias-kuendig thanks for reporting, will try to take a look today.
